//> using scala "3.8.3"
//> using dep org.apache.arrow:arrow-vector:19.0.0
//> using dep org.apache.arrow:arrow-memory:19.0.0
//> using dep org.apache.arrow:arrow-memory-netty:19.0.0
//> using dep com.univocity:univocity-parsers:2.8.4
//> using dep org.apache.parquet:parquet-column:1.14.4
//> using dep org.apache.parquet:parquet-hadoop:1.14.4
//> using dep org.apache.parquet:parquet-arrow:1.14.4
//> using dep org.apache.hadoop:hadoop-common:3.3.6
//> using toolkit default